### PR TITLE
removed deprecated noprealloc flag

### LINKED ISSUE #256: Mongodb noprocess factory
I maintain few postgresql and mongodb related applications and due to a testing requirement change I switched all my postgresql tests to utilize either postgresql_proc or postgresql_noproc depending on a cli parameter. I just found out pytest-mongo does not have a noproc factory.

I think, pytest-mongo features should be on par and in sync with pytest-postgresql.

### PR DESCRIPTION
**Pull request by BrQE**
implemented noproc factory

Fixes #256 .

Changes proposed.

### CODE REVIEW

**Comment by Cediddi** [comment]
Thanks Burak, @fizyk Burak is one of my coworkers and our company assigned this issue to him. If you can review this PR I'll be very happy.

**Review by fizyk — APPROVED** [review]

**Comment by fizyk** [comment]
@Cediddi @BrQE thank you. As soon as the CI passes, I'll merge and release it.

**Comment by Cediddi** [comment]
I think you may need to update your test configuration, as it currently stands, travis does not run a mongodb instance for noop executor. I don't know travis and I don't think @BrQE knows it as well. Can you help fizyk?

**Comment by fizyk** [comment]
@Cediddi the tests, the noproc excetutor connects to the mongodb server started by the mongodb client fixture dependency, so the process should already be there.

**Comment by fizyk** [comment]
Anyway, have you tried to run it locally?

**Comment by Cediddi** [comment]
Burak just pushed a fix to the tests, we worked together and currently all tests pass.

**Review by fizyk — APPROVED** [review]
Everything seems to be working 👍🏻 
Only linters are to be fixed, and ideally README to be updated (in similar fashion as pytest-postgresql)

**Pull request closed without merging**
